name: night_raven_insight_example
description: An example package that uses night_raven_insight for analysis.
version: 4.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  night_raven_insight: ^4.0.0
