name: night_raven_insight
description: >-
  An opinionated analysis configuration that aims to
  enable insightful analysis of your packages.
version: 4.0.0
repository: https://github.com/dart-community/night_raven_insight

topics:
  - analysis
  - lints

environment:
  sdk: ^3.8.0

dependencies:
  dart_flutter_team_lints: ^3.5.2
